# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisdatagathering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='adjectives',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='verbs',
            field=models.IntegerField(null=True),
        ),
    ]
