# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisdatagathering', '0003_auto_20170119_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nouns',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
