# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesisdatagathering', '0004_post_nouns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='adjectives',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nouns',
        ),
        migrations.RemoveField(
            model_name='post',
            name='verbs',
        ),
    ]
